import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Nav from "./ui/nav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const routes = ["Home", "portfolio", "about", "contact"];

  return (
    <html lang="en">

      

      <body className={inter.className}>
        <Nav routes={routes}/>
        {children}
        </body>
      
    </html>
  );
}
